# Generated by Django 5.0.1 on 2024-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, default='masterace.png', upload_to='blog_images/'),
        ),
    ]
